const express = require("express");
const db = require("../db");
const { spawnSync } = require("child_process");
const fs = require("fs");
const path = require("path");
const PDFDocument = require("pdfkit");
const nodemailer = require("nodemailer");

const router = express.Router();

/* =========================
   AUTH GUARD
========================= */
router.use((req, res, next) => {
  if (!req.session || !req.session.faculty) {
    return res.status(401).json({ error: "Unauthorized" });
  }
  next();
});

/* ==================================================
   FEEDBACK → PDF → EMAIL (SINGLE CLICK FLOW)
================================================== */
router.post("/feedback/generate/:studentId", async (req, res) => {
  try {
    const faculty = req.session.faculty;
    const studentId = req.params.studentId;

    /* ---------- FETCH STUDENT ---------- */
    const [[student]] = await db.query(
      `SELECT full_name, register_no, email FROM students WHERE id = ?`,
      [studentId]
    );

    if (!student) {
      return res.status(404).json({ error: "Student not found" });
    }

    /* ---------- GENERATE FEEDBACK (AI) ---------- */
    const py = spawnSync(
      "python",
      ["ai/generate_feedback.py", studentId],
      { encoding: "utf-8" }
    );

    if (py.error || !py.stdout) {
      console.error("PYTHON ERROR:", py.error);
      return res.status(500).json({ error: "Feedback generation failed" });
    }

    const feedbackText = py.stdout.trim();

    /* ---------- SAVE / UPDATE FEEDBACK ---------- */
    await db.query(
      `
      INSERT INTO feedback (student_id, feedback_text, generated_by)
      VALUES (?, ?, ?)
      ON DUPLICATE KEY UPDATE
        feedback_text = VALUES(feedback_text),
        generated_by = VALUES(generated_by)
      `,
      [studentId, feedbackText, faculty.id]
    );

    /* ---------- GENERATE PDF ---------- */
    const pdfDir = path.join(__dirname, "../generated_pdfs");
    if (!fs.existsSync(pdfDir)) fs.mkdirSync(pdfDir);

    const pdfPath = path.join(
      pdfDir,
      `${student.register_no}_Student_Feedback.pdf`
    );

    const doc = new PDFDocument({ margin: 50 });
    const writeStream = fs.createWriteStream(pdfPath);
    doc.pipe(writeStream);

    doc.fontSize(18).text("Alliance University", { align: "center" });
    doc.moveDown(0.5);
    doc.fontSize(13).text("Official Student Feedback Report", {
      align: "center",
    });

    doc.moveDown(2);
    doc.fontSize(11);
    doc.text(`Student Name : ${student.full_name}`);
    doc.text(`Register No  : ${student.register_no}`);
    doc.text(`Faculty      : ${faculty.name}`);
    doc.text(`Generated On : ${new Date().toLocaleDateString()}`);

    doc.moveDown(2);
    doc.text(feedbackText, { align: "justify", lineGap: 4 });

    doc.moveDown(3);
    doc.text("— End of Report —", { align: "center" });

    doc.end();

    /* FIX: wait until PDF is fully written */
    await new Promise((resolve, reject) => {
      writeStream.on("finish", resolve);
      writeStream.on("error", reject);
    });

    /* ---------- SEND EMAIL ---------- */
    /* FIX: correct Gmail SMTP config */
    const transporter = nodemailer.createTransport({
      host: "smtp.gmail.com",
      port: 465,
      secure: true,
      auth: {
        user: process.env.MAIL_USER,
        pass: process.env.MAIL_PASS,
      },
    });

    /* FIX: verify SMTP */
    await transporter.verify();

    await transporter.sendMail({
      from: `"Alliance University" <${process.env.MAIL_USER}>`,
      to: process.env.MAIL_USER,
      subject: "Official Student Feedback Report",
      html: `
        <p>Dear ${student.full_name},</p>

        <p>
          Please find attached your <b>official feedback report</b>
          generated by your faculty mentor from
          <b>Alliance University</b>.
        </p>

        <p>
          This feedback is provided to support your academic
          and professional development.
        </p>

        <p>
          For any clarification, kindly reach out to your
          assigned faculty mentor.
        </p>

        <br>
        <p>
          Regards,<br>
          <b>${faculty.name}</b><br>
          Faculty Mentor<br>
          Alliance University
        </p>
      `,
      attachments: [
        {
          filename: "Student_Feedback_Report.pdf",
          path: pdfPath,
        },
      ],
    });

    res.json({ success: true });

  } catch (err) {
    console.error("FEEDBACK GENERATE + EMAIL ERROR:", err);
    res.status(500).json({
      error: "Failed to generate feedback and send email",
    });
  }
});

/* ==================================================
   ACADEMIC REPORT (UNCHANGED)
================================================== */
router.get("/academic", async (req, res) => {
  try {
    const facultyId = req.session.faculty.id;

    const [rows] = await db.query(
      `
      SELECT id, subject_code, subject_name, semester, exam_phase, row_data
      FROM academic_uploads
      WHERE uploaded_by = ?
      ORDER BY uploaded_at DESC
      `,
      [facultyId]
    );

    const result = [];

    for (const r of rows) {
      const rowData =
        typeof r.row_data === "string"
          ? JSON.parse(r.row_data)
          : r.row_data;

      let prediction = null;
      let confidence = null;

      if (rowData && rowData._features) {
        const py = spawnSync(
          "python",
          ["ai/predict_academic.py", JSON.stringify(rowData._features)],
          { encoding: "utf-8" }
        );

        if (!py.error && py.stdout) {
          const out = JSON.parse(py.stdout);
          prediction = out.prediction;
          confidence = out.confidence;
        }
      }

      result.push({ ...r, ...rowData, prediction, confidence });
    }

    res.json(result);
  } catch (err) {
    console.error("ACADEMIC REPORT ERROR:", err);
    res.status(500).json({ error: "Failed to generate academic report" });
  }
});

/* ==================================================
   SURVEY REPORT (UNCHANGED)
================================================== */
router.get("/survey", async (req, res) => {
  try {
    const facultyId = req.session.faculty.id;

    const [rows] = await db.query(
      `
      SELECT se.*, s.full_name, s.register_no
      FROM survey_evaluation se
      JOIN students s ON s.id = se.student_id
      JOIN mentors m
        ON m.course = s.course
       AND m.section = s.section
      WHERE m.faculty_id = ?
      `,
      [facultyId]
    );

    res.json(rows);
  } catch (err) {
    console.error("SURVEY REPORT ERROR:", err);
    res.status(500).json({ error: "Failed to load survey report" });
  }
});

/* ==================================================
   VIDEO REPORT (UNCHANGED)
================================================== */
router.get("/video", async (req, res) => {
  try {
    const facultyId = req.session.faculty.id;

    const [rows] = await db.query(
      `
      SELECT va.*, s.full_name, s.register_no
      FROM video_analysis va
      JOIN student_videos sv ON sv.id = va.video_id
      JOIN students s ON s.id = sv.student_id
      JOIN mentors m
        ON m.course = s.course
       AND m.section = s.section
      WHERE m.faculty_id = ?
      `,
      [facultyId]
    );

    res.json(rows);
  } catch (err) {
    console.error("VIDEO REPORT ERROR:", err);
    res.status(500).json({ error: "Failed to load video report" });
  }
});

module.exports = router;
