const express = require("express");
const db = require("../db");
const nodemailer = require("nodemailer");
const PDFDocument = require("pdfkit");

const router = express.Router();

/* =====================================================
   AUTH : FACULTY ONLY
===================================================== */
router.use((req, res, next) => {
  if (!req.session?.faculty) {
    return res.status(401).json({ error: "Unauthorized" });
  }
  next();
});

/* =====================================================
   MAIL TRANSPORT (GMAIL)
===================================================== */
const mailTransporter = nodemailer.createTransport({
  service: "gmail",
  auth: {
    user: process.env.MAIL_USER,
    pass: process.env.MAIL_PASS
  }
});

/* =====================================================
   SEND EXISTING FEEDBACK AS PDF TO STUDENT EMAIL
===================================================== */
router.post("/send/:studentId", async (req, res) => {
  const facultyId = req.session.faculty.id;
  const studentId = req.params.studentId;

  try {
    /* ---------- ACCESS VALIDATION ---------- */
    const [[access]] = await db.query(`
      SELECT s.id
      FROM mentors m
      JOIN students s
        ON s.course = m.course
       AND s.section = m.section
      WHERE m.faculty_id = ?
        AND s.id = ?
    `, [facultyId, studentId]);

    if (!access) {
      return res.status(403).json({ error: "Access denied" });
    }

    /* ---------- FETCH STUDENT & FEEDBACK ---------- */
    const [[data]] = await db.query(`
      SELECT 
        s.full_name,
        s.register_no,
        s.email,
        f.feedback_text,
        f.generated_at
      FROM students s
      JOIN student_feedback f ON f.student_id = s.id
      WHERE s.id = ?
    `, [studentId]);

    if (!data || !data.feedback_text) {
      return res.status(400).json({ error: "Feedback not available" });
    }

    /* ---------- PDF GENERATION ---------- */
    const pdfBuffer = await createFeedbackPDF(data);

    /* ---------- EMAIL SENDING ---------- */
    await mailTransporter.sendMail({
      from: `"Alliance University" <${process.env.MAIL_USER}>`,
      to: data.email,
      subject: "Academic Feedback Report – Alliance University",
      text: `
Dear ${data.full_name},

Please find attached your Academic Feedback Report issued by Alliance University.

This feedback has been prepared after a comprehensive academic evaluation and is intended to support your academic growth and improvement.

If you have any questions, please contact your faculty mentor.

Regards,
Alliance University
`,
      attachments: [
        {
          filename: `Alliance_Feedback_${data.register_no}.pdf`,
          content: pdfBuffer
        }
      ]
    });

    res.json({ success: true, message: "Feedback emailed successfully" });

  } catch (err) {
    console.error("Faculty Feedback Email Error:", err);
    res.status(500).json({ error: "Internal server error" });
  }
});

/* =====================================================
   PDF CREATION (PROFESSIONAL FORMAT)
===================================================== */
function createFeedbackPDF(data) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const buffers = [];

    doc.on("data", buffers.push.bind(buffers));
    doc.on("end", () => resolve(Buffer.concat(buffers)));
    doc.on("error", reject);

    /* ---- HEADER ---- */
    doc.fontSize(18).text("Alliance University", { align: "center" });
    doc.fontSize(14).text("Academic Feedback Report", { align: "center" });
    doc.moveDown(2);

    /* ---- STUDENT INFO ---- */
    doc.fontSize(12).text(`Student Name   : ${data.full_name}`);
    doc.text(`Register Number: ${data.register_no}`);
    doc.text(`Report Date    : ${new Date(data.generated_at).toLocaleDateString()}`);
    doc.moveDown();

    /* ---- FEEDBACK ---- */
    doc.fontSize(13).text("Faculty Feedback", { underline: true });
    doc.moveDown(0.5);

    doc.fontSize(11).text(data.feedback_text, {
      lineGap: 4,
      align: "left"
    });

    /* ---- FOOTER ---- */
    doc.moveDown(2);
    doc.fontSize(9).text(
      "This is an official academic document generated by Alliance University.",
      { align: "center", color: "gray" }
    );

    doc.end();
  });
}

module.exports = router;
